!cloudgene.mapred.util.Settings
name: Cloudgene WF
apps:
  - id: wordcount
    permission: user
    filename: applications/Examples/files/wordcount-mr-step.yaml
hadoopPath: /usr
hdfsWorkspace: cloudgene-workspace-hdfs
localWorkspace: cloudgene-workspace-local
mail:
   port:
   smtp:
   name:
   password:
   user:
maxRunningJobs: 10
maxRunningJobsPerUser: 1
notificationAfter: 7
retireAfter: 10
removeHdfsWorkspace: true
streaming: false
streamingJar: /usr/contrib/streaming/hadoop-streaming-2.6.0-cdh5.4.5.jar
